<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>PCMHammerAvalonia</RootNamespace>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" />
		<PackageReference Include="Avalonia.Controls.WebView" />
		<PackageReference Include="Avalonia.Themes.Fluent" />
		<PackageReference Include="Avalonia.Fonts.Inter" />
		<PackageReference Include="AvaloniaUI.DiagnosticsSupport">
			<IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
			<PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
		</PackageReference>
		<PackageReference Include="CommunityToolkit.Mvvm" />
	</ItemGroup>

	<!-- Cross-platform references -->
	<ItemGroup>
	  <PackageReference Include="FluentIcons.Avalonia.Fluent" />
	</ItemGroup>

	<!-- Windows-only reference: completely omitted from Android builds -->
	<ItemGroup Condition="'$(TargetPlatformIdentifier)' != 'android'">
		<ProjectReference Include="..\..\..\PcmLibrary\PcmLibrary.csproj" />
		<ProjectReference Include="..\..\..\J2534DotNet\J2534DotNet\J2534DotNet.csproj" />
		<ProjectReference Include="..\..\..\PcmLibraryWindowsApi\PcmLibraryWindowsApi.csproj" />
	</ItemGroup>

</Project>